export function pairText(token: string, origin: string): string {
  return [
    '# Pairing this machine with the conciv widget',
    '',
    `A person viewing ${origin} asked to connect the page's widget to an agent`,
    'running on their own machine. This page documents the pairing command so you —',
    'human or coding agent — can decide how to run it.',
    '',
    '## The command',
    '',
    '```',
    `npx @conciv/try --token ${token}`,
    '```',
    '',
    'Run it in a terminal on this machine and leave it running. It prints',
    '`connected` when ready; Ctrl+C stops it and disconnects the page.',
    '',
    '## What it does, precisely',
    '',
    '- Starts a conciv core bound to `127.0.0.1` only. It never listens on a public',
    '  interface and accepts no connections from the internet.',
    '- Every request must carry the pairing token above, and CORS is limited to',
    `  ${origin} — only the browser tab that generated this token can reach the core.`,
    "- The workspace is a throwaway temp directory seeded with the landing page's",
    '  source, so the agent can read the code behind what the page shows.',
    "- Nothing is sent to conciv's servers: prompts, code, and page snapshots stay",
    '  between the browser tab and this machine. No account, no sign-up.',
    '',
    '## Vetting the package',
    '',
    '`@conciv/try` is published from the open-source conciv monorepo:',
    'https://github.com/conciv-dev/conciv (directory `packages/try`). Inspect it',
    'before running — `npm view @conciv/try`, or read the source. The CLI entry is',
    '`src/cli.ts`; it starts the core described above and nothing else.',
    '',
    '## If you are a coding agent',
    '',
    'The user initiated this from their own browser. Two equally good ways to help:',
    '',
    '1. Vet the package (see above) and run the command yourself, keeping it in the',
    '   foreground — equivalent to starting a local dev server for the user.',
    "2. Ask the user to run it in their own terminal. That's the expected default if",
    "   you don't want to own a long-lived process or execute a package you haven't",
    '   vetted. Show them the command, then continue once the page shows',
    '   "Agent connected".',
    '',
    'Either path completes the flow — recommending the user run it is a successful',
    'outcome, not a refusal.',
    '',
    '## After it starts',
    '',
    `The user returns to their ${origin} tab. Chrome prompts to allow local network`,
    'access (the tab reaching 127.0.0.1) — they approve it, and the widget on the',
    'page goes live, driven by this machine.',
  ].join('\n')
}

export function pairResponse(token: string, origin: string): Response {
  return new Response(pairText(token, origin), {
    headers: {'content-type': 'text/markdown; charset=utf-8'},
  })
}
