import type {Theme} from '@unocss/preset-wind4'

export const colors = {
  'chat-accent': 'var(--chat-accent)',
  'chat-accent-hi': 'var(--chat-accent-hi)',
  'chat-accent-link': 'var(--chat-accent-link)',
  'chat-accent-08': 'var(--chat-accent-08)',
  'chat-accent-20': 'var(--chat-accent-20)',
  'chat-accent-line': 'var(--chat-accent-line)',

  'chat-panel': 'var(--chat-panel)',
  'chat-panel-sunk': 'var(--chat-panel-sunk)',
  'chat-glass': 'var(--chat-glass)',
  'chat-fill': 'var(--chat-fill)',
  'chat-fill-soft': 'var(--chat-fill-soft)',
  'chat-fill-strong': 'var(--chat-fill-strong)',
  'chat-sunken': 'var(--chat-sunken)',

  'chat-text': 'var(--chat-text)',
  'chat-text-hi': 'var(--chat-text-hi)',
  'chat-text-2': 'var(--chat-text-2)',
  'chat-text-3': 'var(--chat-text-3)',
  'chat-on-accent': 'var(--chat-on-accent)',

  'chat-agent': 'var(--chat-agent)',
  'chat-danger': 'var(--chat-danger)',
  'chat-danger-line': 'var(--chat-danger-line)',
  'chat-success': 'var(--chat-success)',
  'chat-warn': 'var(--chat-warn)',
  'chat-dim': 'var(--chat-dim)',

  'chat-line': 'var(--chat-line)',
  'chat-line-2': 'var(--chat-line-2)',
  'chat-line-soft': 'var(--chat-line-soft)',

  'chat-read': 'color-mix(in oklch, var(--chat-accent) 30%, var(--chat-agent))',
  'chat-danger-10': 'color-mix(in oklch, var(--chat-danger) 10%, transparent)',
  'chat-danger-14': 'color-mix(in oklch, var(--chat-danger) 14%, transparent)',
  'chat-success-18': 'color-mix(in oklch, var(--chat-success) 18%, transparent)',
  'chat-warn-20': 'color-mix(in oklch, var(--chat-warn) 20%, transparent)',
  'chat-panel-60': 'color-mix(in srgb, var(--chat-panel) 60%, transparent)',

  'chat-status-running': 'var(--chat-status-running)',
  'chat-status-waiting': 'var(--chat-status-waiting)',
  'chat-status-failed': 'var(--chat-status-failed)',
  'chat-status-done': 'var(--chat-status-done)',
  'chat-on-status': 'var(--chat-on-status)',

  'chat-glyph': 'var(--chat-glyph)',
  'chat-target': 'var(--chat-target)',
  'chat-summary': 'var(--chat-summary)',
  'chat-prompt': 'var(--chat-prompt)',
  'chat-body-settled': 'var(--chat-body-settled)',
  'chat-action': 'var(--chat-action)',
  'chat-mono-lift': 'var(--chat-mono-lift)',
  'chat-microlabel': 'var(--chat-microlabel)',
  'chat-faint': 'var(--chat-faint)',
  'chat-hint': 'var(--chat-hint)',
  'chat-separator': 'var(--chat-separator)',
  'chat-affordance': 'var(--chat-affordance)',
  'chat-queue-bg': 'var(--chat-queue-bg)',

  'chat-frame-bg': 'var(--chat-frame-bg)',
  'chat-frame-line': 'var(--chat-frame-line)',
  'chat-frame-line-error': 'var(--chat-frame-line-error)',
  'chat-frame-text': 'var(--chat-frame-text)',
  'chat-frame-text-error': 'var(--chat-frame-text-error)',

  'chat-perm-bg': 'var(--chat-perm-bg)',
  'chat-perm-line': 'var(--chat-perm-line)',
  'chat-perm-chip-bg': 'var(--chat-perm-chip-bg)',
  'chat-perm-label': 'var(--chat-perm-label)',
  'chat-perm-path': 'var(--chat-perm-path)',

  'chat-rail-bg': 'var(--chat-rail-bg)',
  'chat-statusbar-bg': 'var(--chat-statusbar-bg)',
  'chat-ground': 'var(--chat-ground)',

  'chat-selection-bg': 'var(--chat-selection-bg)',
} satisfies Theme['colors']
