import {schema, col} from 'jazz-tools'

export const app = schema.defineApp({
  canvasElements: schema.table({
    room: col.string(),
    elementId: col.string(),
    data: col.json(),
    version: col.int(),
  }),
  canvasPending: schema.table({
    room: col.string(),
    kind: col.enum('skeletons', 'mermaid'),
    payload: col.json(),
  }),
  comments: schema.table({
    previewId: col.string(),
    sessionId: col.string(),
    cid: col.string(),
    threadId: col.string(),
    parentId: col.string().optional(),
    parts: col.json(),
    authorKind: col.enum('human', 'ai'),
    authorModel: col.string().optional(),
    status: col.enum('open', 'resolved', 'drifted', 'orphaned').default('open'),
    kind: col.enum('source-linked', 'floating'),
    anchor: col.json().optional(),
    anchorFile: col.string().optional(),
    anchorComponent: col.string().optional(),
    anchorHash: col.string().optional(),
    lastResolvedCommit: col.string().optional(),
    lastResolvedFileHash: col.string().optional(),
    createdAt: col.timestamp(),
    updatedAt: col.timestamp(),
    resolvedAt: col.timestamp().optional(),
    resolvedBy: col.string().optional(),
  }),
  pins: schema.table({
    room: col.string(),
    cid: col.string(),
    x: col.float(),
    y: col.float(),
    elementId: col.string().optional(),
    pinState: col.enum('locked', 'offset').default('locked'),
    anchorX: col.float().optional(),
    anchorY: col.float().optional(),
  }),
  cursors: schema.table({
    room: col.string(),
    sessionId: col.string(),
    x: col.float(),
    y: col.float(),
    name: col.string(),
    color: col.string(),
    lastSeen: col.timestamp(),
  }),
})
