import {mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {describe, expect, it} from 'vitest'
import {generateExtensionsEntrySource, writeExtensionsEntry} from '../src/core/extensions-entry.js'

function makeProject(): string {
  return mkdtempSync(join(tmpdir(), 'conciv-entry-'))
}

function seedExtensionsDir(root: string): string {
  const dir = join(root, 'conciv', 'extensions')
  mkdirSync(dir, {recursive: true})
  return dir
}

describe('generateExtensionsEntrySource', () => {
  it('emits sorted extensionless imports and provenance sources in filename order', () => {
    const source = generateExtensionsEntrySource(['b.tsx', 'a.ts'])
    expect(source).toContain('// generated by conciv — do not edit')
    expect(source).toContain("import extension0 from '../conciv/extensions/a'")
    expect(source).toContain("import extension1 from '../conciv/extensions/b'")
    expect(source).toContain(
      "export const entries = [{extension: extension0, source: '/conciv/extensions/a.ts'}, {extension: extension1, source: '/conciv/extensions/b.tsx'}]",
    )
  })

  it('byte-matches the spike shape for a single extension (no semicolons, single quotes)', () => {
    const source = generateExtensionsEntrySource(['tanstack.tsx'])
    expect(source).toBe(
      '// generated by conciv — do not edit\n' +
        "import extension0 from '../conciv/extensions/tanstack'\n" +
        "export const entries = [{extension: extension0, source: '/conciv/extensions/tanstack.tsx'}]\n",
    )
  })

  it('binds a hyphenated basename to a valid index identifier with an extensionless specifier', () => {
    const source = generateExtensionsEntrySource(['deploy-button.tsx'])
    expect(source).toContain("import extension0 from '../conciv/extensions/deploy-button'")
    expect(source).toContain("{extension: extension0, source: '/conciv/extensions/deploy-button.tsx'}")
    expect(source).not.toContain(';')
    expect(source).not.toContain('"')
  })

  it('throws naming both files when two inputs share an extensionless basename', () => {
    expect(() => generateExtensionsEntrySource(['foo.ts', 'foo.tsx'])).toThrow(/foo\.ts/)
    expect(() => generateExtensionsEntrySource(['foo.ts', 'foo.tsx'])).toThrow(/foo\.tsx/)
  })

  it('emits an empty entries array for empty input', () => {
    expect(generateExtensionsEntrySource([])).toContain('export const entries = []')
  })
})

describe('writeExtensionsEntry', () => {
  it('lists only real extension files (sorted), ignoring d.ts, non-tsx, and subdirectories', () => {
    const root = makeProject()
    const dir = seedExtensionsDir(root)
    writeFileSync(join(dir, 'b.tsx'), 'export default {}')
    writeFileSync(join(dir, 'a.ts'), 'export default {}')
    writeFileSync(join(dir, 'types.d.ts'), 'export {}')
    writeFileSync(join(dir, 'notes.md'), 'hi')
    mkdirSync(join(dir, 'nested.ts'), {recursive: true})

    const result = writeExtensionsEntry(root)
    const content = readFileSync(result.path, 'utf8')
    expect(content).toContain("import extension0 from '../conciv/extensions/a'")
    expect(content).toContain("import extension1 from '../conciv/extensions/b'")
    expect(content).not.toContain('types')
    expect(content).not.toContain('notes')
    expect(content).not.toContain('nested')
    expect(result.path).toBe(join(root, '.conciv', 'extensions-client.gen.tsx'))
  })

  it('writes an empty-entries file for a missing extensions dir', () => {
    const root = makeProject()
    const result = writeExtensionsEntry(root)
    expect(result.changed).toBe(true)
    expect(readFileSync(result.path, 'utf8')).toContain('export const entries = []')
  })

  it('is idempotent: second write leaves the file untouched, third write reacts to a new stub', () => {
    const root = makeProject()
    const dir = seedExtensionsDir(root)
    writeFileSync(join(dir, 'a.ts'), 'export default {}')

    const first = writeExtensionsEntry(root)
    expect(first.changed).toBe(true)
    const firstMtime = statSync(first.path).mtimeMs

    const second = writeExtensionsEntry(root)
    expect(second.changed).toBe(false)
    expect(statSync(second.path).mtimeMs).toBe(firstMtime)

    writeFileSync(join(dir, 'b.tsx'), 'export default {}')
    const third = writeExtensionsEntry(root)
    expect(third.changed).toBe(true)
    expect(readFileSync(third.path, 'utf8')).toContain("import extension1 from '../conciv/extensions/b'")
  })
})
