import {mkdirSync, readFileSync, writeFileSync} from 'node:fs'
import {join} from 'node:path'
import {listExtensionFiles} from '@conciv/extension-compiler/extensions'
import {genImport} from 'knitwork'

const HEADER = '// generated by conciv — do not edit'
const ENTRY_DIR = '.conciv'
const ENTRY_FILE = 'extensions-client.gen.tsx'

function stemOf(file: string): string {
  const dot = file.lastIndexOf('.')
  return dot === -1 ? file : file.slice(0, dot)
}

function stripTrailingSemicolon(line: string): string {
  return line.endsWith(';') ? line.slice(0, -1) : line
}

function assertUniqueStems(files: readonly string[]): void {
  const seen = new Map<string, string>()
  for (const file of files) {
    const stem = stemOf(file)
    const previous = seen.get(stem)
    if (previous !== undefined) {
      throw new Error(
        `conciv: extension files "${previous}" and "${file}" both resolve to the extensionless specifier ../conciv/extensions/${stem}; rename one so the import is unambiguous`,
      )
    }
    seen.set(stem, file)
  }
}

export function generateExtensionsEntrySource(files: readonly string[]): string {
  const sorted = files.toSorted()
  assertUniqueStems(sorted)
  const imports = sorted.map((file, index) =>
    stripTrailingSemicolon(
      genImport(`../conciv/extensions/${stemOf(file)}`, `extension${index}`, {singleQuotes: true}),
    ),
  )
  const elements = sorted.map((file, index) => `{extension: extension${index}, source: '/conciv/extensions/${file}'}`)
  return [HEADER, ...imports, `export const entries = [${elements.join(', ')}]`, ''].join('\n')
}

function isMissingFileError(error: unknown): boolean {
  return typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT'
}

function readExisting(path: string): string | undefined {
  try {
    return readFileSync(path, 'utf8')
  } catch (error) {
    if (isMissingFileError(error)) return undefined
    throw error
  }
}

export function writeExtensionsEntry(root: string): {path: string; changed: boolean} {
  const source = generateExtensionsEntrySource(listExtensionFiles(root))
  const dir = join(root, ENTRY_DIR)
  mkdirSync(dir, {recursive: true})
  const path = join(dir, ENTRY_FILE)
  if (readExisting(path) === source) return {path, changed: false}
  writeFileSync(path, source, 'utf8')
  return {path, changed: true}
}
