/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PairTokenRouteImport } from './routes/pair.$token'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PairTokenRoute = PairTokenRouteImport.update({
  id: '/pair/$token',
  path: '/pair/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/pair/$token': typeof PairTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/pair/$token': typeof PairTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/pair/$token': typeof PairTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/pair/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/pair/$token'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/pair/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  PairTokenRoute: typeof PairTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair/$token': {
      id: '/pair/$token'
      path: '/pair/$token'
      fullPath: '/pair/$token'
      preLoaderRoute: typeof PairTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  PairTokenRoute: PairTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
