/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipSessionIdRouteImport } from './routes/pip.$sessionId'
import { Route as PanelSettingsRouteImport } from './routes/panel.settings'
import { Route as PanelLatestRouteImport } from './routes/panel.latest'
import { Route as PanelConnectRouteImport } from './routes/panel.connect'
import { Route as PanelSessionIdRouteImport } from './routes/panel.$sessionId'
import { Route as PanelSettingsIndexRouteImport } from './routes/panel.settings.index'
import { Route as PanelSessionIdIndexRouteImport } from './routes/panel.$sessionId.index'
import { Route as PanelSettingsAppearanceRouteImport } from './routes/panel.settings.appearance'
import { Route as PanelSessionIdViewRouteImport } from './routes/panel.$sessionId.$view'

const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipSessionIdRoute = PipSessionIdRouteImport.update({
  id: '/pip/$sessionId',
  path: '/pip/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelSettingsRoute = PanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PanelRoute,
} as any)
const PanelLatestRoute = PanelLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => PanelRoute,
} as any)
const PanelConnectRoute = PanelConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSessionIdRoute = PanelSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSettingsIndexRoute = PanelSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelSettingsRoute,
} as any)
const PanelSessionIdIndexRoute = PanelSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelSessionIdRoute,
} as any)
const PanelSettingsAppearanceRoute = PanelSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => PanelSettingsRoute,
} as any)
const PanelSessionIdViewRoute = PanelSessionIdViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => PanelSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/quick': typeof QuickRoute
  '/panel/$sessionId': typeof PanelSessionIdRouteWithChildren
  '/panel/connect': typeof PanelConnectRoute
  '/panel/latest': typeof PanelLatestRoute
  '/panel/settings': typeof PanelSettingsRouteWithChildren
  '/pip/$sessionId': typeof PipSessionIdRoute
  '/panel/$sessionId/$view': typeof PanelSessionIdViewRoute
  '/panel/settings/appearance': typeof PanelSettingsAppearanceRoute
  '/panel/$sessionId/': typeof PanelSessionIdIndexRoute
  '/panel/settings/': typeof PanelSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/quick': typeof QuickRoute
  '/panel/connect': typeof PanelConnectRoute
  '/panel/latest': typeof PanelLatestRoute
  '/pip/$sessionId': typeof PipSessionIdRoute
  '/panel/$sessionId/$view': typeof PanelSessionIdViewRoute
  '/panel/settings/appearance': typeof PanelSettingsAppearanceRoute
  '/panel/$sessionId': typeof PanelSessionIdIndexRoute
  '/panel/settings': typeof PanelSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/quick': typeof QuickRoute
  '/panel/$sessionId': typeof PanelSessionIdRouteWithChildren
  '/panel/connect': typeof PanelConnectRoute
  '/panel/latest': typeof PanelLatestRoute
  '/panel/settings': typeof PanelSettingsRouteWithChildren
  '/pip/$sessionId': typeof PipSessionIdRoute
  '/panel/$sessionId/$view': typeof PanelSessionIdViewRoute
  '/panel/settings/appearance': typeof PanelSettingsAppearanceRoute
  '/panel/$sessionId/': typeof PanelSessionIdIndexRoute
  '/panel/settings/': typeof PanelSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/quick'
    | '/panel/$sessionId'
    | '/panel/connect'
    | '/panel/latest'
    | '/panel/settings'
    | '/pip/$sessionId'
    | '/panel/$sessionId/$view'
    | '/panel/settings/appearance'
    | '/panel/$sessionId/'
    | '/panel/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel'
    | '/quick'
    | '/panel/connect'
    | '/panel/latest'
    | '/pip/$sessionId'
    | '/panel/$sessionId/$view'
    | '/panel/settings/appearance'
    | '/panel/$sessionId'
    | '/panel/settings'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/quick'
    | '/panel/$sessionId'
    | '/panel/connect'
    | '/panel/latest'
    | '/panel/settings'
    | '/pip/$sessionId'
    | '/panel/$sessionId/$view'
    | '/panel/settings/appearance'
    | '/panel/$sessionId/'
    | '/panel/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
  QuickRoute: typeof QuickRoute
  PipSessionIdRoute: typeof PipSessionIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip/$sessionId': {
      id: '/pip/$sessionId'
      path: '/pip/$sessionId'
      fullPath: '/pip/$sessionId'
      preLoaderRoute: typeof PipSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/settings': {
      id: '/panel/settings'
      path: '/settings'
      fullPath: '/panel/settings'
      preLoaderRoute: typeof PanelSettingsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/latest': {
      id: '/panel/latest'
      path: '/latest'
      fullPath: '/panel/latest'
      preLoaderRoute: typeof PanelLatestRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/connect': {
      id: '/panel/connect'
      path: '/connect'
      fullPath: '/panel/connect'
      preLoaderRoute: typeof PanelConnectRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/$sessionId': {
      id: '/panel/$sessionId'
      path: '/$sessionId'
      fullPath: '/panel/$sessionId'
      preLoaderRoute: typeof PanelSessionIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/settings/': {
      id: '/panel/settings/'
      path: '/'
      fullPath: '/panel/settings/'
      preLoaderRoute: typeof PanelSettingsIndexRouteImport
      parentRoute: typeof PanelSettingsRoute
    }
    '/panel/$sessionId/': {
      id: '/panel/$sessionId/'
      path: '/'
      fullPath: '/panel/$sessionId/'
      preLoaderRoute: typeof PanelSessionIdIndexRouteImport
      parentRoute: typeof PanelSessionIdRoute
    }
    '/panel/settings/appearance': {
      id: '/panel/settings/appearance'
      path: '/appearance'
      fullPath: '/panel/settings/appearance'
      preLoaderRoute: typeof PanelSettingsAppearanceRouteImport
      parentRoute: typeof PanelSettingsRoute
    }
    '/panel/$sessionId/$view': {
      id: '/panel/$sessionId/$view'
      path: '/$view'
      fullPath: '/panel/$sessionId/$view'
      preLoaderRoute: typeof PanelSessionIdViewRouteImport
      parentRoute: typeof PanelSessionIdRoute
    }
  }
}

interface PanelSessionIdRouteChildren {
  PanelSessionIdViewRoute: typeof PanelSessionIdViewRoute
  PanelSessionIdIndexRoute: typeof PanelSessionIdIndexRoute
}

const PanelSessionIdRouteChildren: PanelSessionIdRouteChildren = {
  PanelSessionIdViewRoute: PanelSessionIdViewRoute,
  PanelSessionIdIndexRoute: PanelSessionIdIndexRoute,
}

const PanelSessionIdRouteWithChildren = PanelSessionIdRoute._addFileChildren(
  PanelSessionIdRouteChildren,
)

interface PanelSettingsRouteChildren {
  PanelSettingsAppearanceRoute: typeof PanelSettingsAppearanceRoute
  PanelSettingsIndexRoute: typeof PanelSettingsIndexRoute
}

const PanelSettingsRouteChildren: PanelSettingsRouteChildren = {
  PanelSettingsAppearanceRoute: PanelSettingsAppearanceRoute,
  PanelSettingsIndexRoute: PanelSettingsIndexRoute,
}

const PanelSettingsRouteWithChildren = PanelSettingsRoute._addFileChildren(
  PanelSettingsRouteChildren,
)

interface PanelRouteChildren {
  PanelSessionIdRoute: typeof PanelSessionIdRouteWithChildren
  PanelConnectRoute: typeof PanelConnectRoute
  PanelLatestRoute: typeof PanelLatestRoute
  PanelSettingsRoute: typeof PanelSettingsRouteWithChildren
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelSessionIdRoute: PanelSessionIdRouteWithChildren,
  PanelConnectRoute: PanelConnectRoute,
  PanelLatestRoute: PanelLatestRoute,
  PanelSettingsRoute: PanelSettingsRouteWithChildren,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
  QuickRoute: QuickRoute,
  PipSessionIdRoute: PipSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
