import {chatColors, chatEase, chatFont, chatRadius} from '@conciv/uno-preset'
import {
  SKIN_ANCHOR_DOCS,
  SKIN_ANCHOR_GROUPS,
  SKIN_SCALAR_ANCHORS,
  SKIN_SCHEME_ANCHORS,
  anchorTokenDefinitions,
  skinClassName,
  type SkinAnchorName,
} from '../src/skin-contract.ts'
import {DERIVED_TOKENS} from '../src/derived-tokens.ts'
import {ALL_SKINS, BASE_SKIN} from './generated-skins.ts'

const GENERATED_BY = 'packages/ui-kit-system/scripts/gen-tokens.ts'

const ALL_ANCHORS: SkinAnchorName[] = [...SKIN_SCHEME_ANCHORS, ...SKIN_SCALAR_ANCHORS]
const SCHEME_ANCHORS = new Set<string>(SKIN_SCHEME_ANCHORS)
const BASE_TOKENS = anchorTokenDefinitions(BASE_SKIN)

function banner(title: string, intro: string): string {
  return `# ${title}\n\n<!-- Generated by ${GENERATED_BY}. Run \`pnpm --filter @conciv/ui-kit-system gen:tokens\` after editing a skin. -->\n\n${intro}`
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|')
}

function anchorTable(): string {
  const sections = SKIN_ANCHOR_GROUPS.map((group) => {
    const rows = ALL_ANCHORS.filter((name) => SKIN_ANCHOR_DOCS[name].group === group).map((name) => {
      const shape = SCHEME_ANCHORS.has(name) ? '`{light, dark}`' : 'single value'
      return `| \`--${name}\` | ${shape} | ${escapeCell(SKIN_ANCHOR_DOCS[name].description)} |`
    })
    return `### ${group}\n\n| anchor | shape | meaning |\n| --- | --- | --- |\n${rows.join('\n')}\n`
  })
  return sections.join('\n')
}

function skinTable(): string {
  const rows = ALL_SKINS.map((skin) => {
    const selection = skin.name === BASE_SKIN.name ? 'default, no class' : `\`.${skinClassName(skin.name)}\``
    return `| \`${skin.name}\` | ${escapeCell(skin.label)} | ${selection} | ${escapeCell(skin.description)} |`
  })
  return `| name | label | applied as | look |\n| --- | --- | --- | --- |\n${rows.join('\n')}\n`
}

export function renderSkinContractDoc(): string {
  const intro = `A skin is a typed object in \`packages/ui-kit-system/src/skin-<name>.ts\`. It sets **only** the ${ALL_ANCHORS.length} anchors below; every other \`--chat-*\` custom property is internal, derived once from these anchors in the base sheet, and not writable by a skin. Omitting an anchor, or either half of a \`{light, dark}\` pair, is a compile error.

A host page selects a skin by declaring the \`--conciv-skin\` custom property on \`html\` or \`body\`:

\`\`\`css
html {
  --conciv-skin: terminal;
}
\`\`\`

An unknown or absent value falls back to \`${BASE_SKIN.name}\` with one console warning. The detector re-reads the property on the same signals as colour-scheme detection: \`class\`, \`style\` and \`data-theme\` mutations on \`html\` and \`body\`. A stylesheet-only change that flips none of those does not live-update.

The widget stamps the resolved skin as a class on every render root it owns, so portalled menus, the effects overlay and popped-out windows all follow.

## Shipped skins

${skinTable()}
## Anchors

${anchorTable()}
## Rules

- Colour and shadow anchors are \`{light, dark}\` pairs and are emitted as one \`light-dark()\` declaration each, so a skin is complete for both schemes by construction.
- The skin class always lands on the same element as the colour-scheme class. That co-location is load-bearing: the production build lowers \`light-dark()\` into helper custom properties that resolve at the declaring element.
- Hand-tuned semantics (the agent hue, permission gold, rail and status-bar surfaces, diff backgrounds, the Shiki palette) stay internal and identical across skins. Skins retint the anchors; semantics stay consistent.
- \`--chat-space\` scales the spacing base of the conversation surfaces only (thread and composer). Frame geometry, fixed placements and arbitrary-value CSS do not follow it. Stay within roughly 8% of \`0.25rem\`.
- Every skin's colour pairs are checked for WCAG contrast in CI. An inaccessible skin fails the build.
`
  return banner('Skin author contract', intro)
}

function tokenTable(names: string[], source: Record<string, {description: string}>): string {
  const rows = names.map((name) => `| \`--${name}\` | ${escapeCell(source[name]?.description ?? '')} |`)
  return `| token | meaning |\n| --- | --- |\n${rows.join('\n')}\n`
}

function utilityTable(title: string, usage: string, entries: Record<string, string>): string {
  const rows = Object.entries(entries).map(([key, value]) => `| \`${key}\` | \`${escapeCell(value)}\` |`)
  return `### ${title}\n\nUsed as ${usage}.\n\n| name | resolves to |\n| --- | --- |\n${rows.join('\n')}\n`
}

export function renderExtensionContractDoc(): string {
  const intro = `Extensions are components inside the widget's surface, not owners of its look. Style exclusively through the tokens and utilities below and your extension renders correctly under every skin and colour scheme with no per-skin work.

There is no per-extension theme override. If you need a bespoke colour, derive it locally from a public token:

\`\`\`css
.my-extension-card {
  --my-card-tint: color-mix(in oklch, var(--chat-accent) 12%, transparent);
  background: var(--my-card-tint);
  border: 1px solid var(--chat-line);
  border-radius: var(--chat-radius-md);
  color: var(--chat-text);
}
\`\`\`

Never key off a skin class: \`.${skinClassName('terminal')}\` and friends are an internal application mechanism, not a selector surface.

## Stable tokens

These resolve under every skin. Colour tokens follow the active colour scheme on their own.

### anchors

${tokenTable(ALL_ANCHORS, BASE_TOKENS)}
### derived

${tokenTable(Object.keys(DERIVED_TOKENS), DERIVED_TOKENS)}
## Stable utilities

${utilityTable('colours', '`bg-*`, `text-*`, `border-*`', chatColors)}
${utilityTable('radii', '`rounded-*`', chatRadius)}
${utilityTable('fonts', '`font-*`', chatFont)}
${utilityTable('easing', '`ease-*`', chatEase)}
## Spacing

Spacing utilities (\`p-*\`, \`gap-*\`, \`m-*\`) are stable. Inside the thread and composer they scale with the active skin's \`--chat-space\`; elsewhere they use the widget default.
`
  return banner('Extension author contract', intro)
}
