/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PostsPostIdRouteImport } from "./routes/posts.$postId"
import { Route as IndexRouteImport } from "./routes/index"

const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: "/posts/$postId",
  path: "/posts/$postId",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export const routeTree = rootRouteImport
