import type {KeyedTokensInfo} from '@shikijs/magic-move/types'

export type SnippetHover = {target: string; occurrence: number; html: string; docs: string | null}
export type SnippetCompletion = {target: string; items: string[]}
export type SnippetTwoslash = {id: string; hovers: SnippetHover[]; completion: SnippetCompletion | null}

export const MAGIC_MOVE_STEP_IDS: string[] = ['vite', 'nextjs', 'webpack', 'rspack']

export const MAGIC_MOVE_STEPS: KeyedTokensInfo[] = [
  {
    code: "import {defineConfig} from 'vite'\nimport conciv, {type ConcivConfig} from '@conciv/it/plugin/vite'\n\nconst options: ConcivConfig = {\n  h\n}\n\nexport default defineConfig({\n  plugins: [conciv(options)],\n})",
    hash: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ',
    tokens: [
      {
        content: 'import',
        offset: 0,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-0',
      },
      {content: ' ', offset: 6, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-1'},
      {
        content: '{defineConfig}',
        offset: 7,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-2',
      },
      {content: ' ', offset: 21, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-3'},
      {
        content: 'from',
        offset: 22,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-4',
      },
      {
        content: ' ',
        offset: 26,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-5',
      },
      {
        content: "'vite'",
        offset: 27,
        htmlStyle: {color: '#032F62', '--shiki-dark': '#9ECBFF'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-6',
      },
      {content: '\n', offset: 33, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-7'},
      {
        content: 'import',
        offset: 34,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-8',
      },
      {content: ' ', offset: 40, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-9'},
      {
        content: 'conciv, {',
        offset: 41,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-10',
      },
      {
        content: 'type',
        offset: 50,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-11',
      },
      {content: ' ', offset: 54, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-12'},
      {
        content: 'ConcivConfig}',
        offset: 55,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-13',
      },
      {content: ' ', offset: 68, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-14'},
      {
        content: 'from',
        offset: 69,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-15',
      },
      {
        content: ' ',
        offset: 73,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-16',
      },
      {
        content: "'@conciv/it/plugin/vite'",
        offset: 74,
        htmlStyle: {color: '#032F62', '--shiki-dark': '#9ECBFF'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-17',
      },
      {content: '\n', offset: 98, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-18'},
      {content: '\n', offset: 99, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-19'},
      {
        content: 'const',
        offset: 100,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-20',
      },
      {
        content: ' ',
        offset: 105,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-21',
      },
      {
        content: 'options',
        offset: 106,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-22',
      },
      {
        content: ':',
        offset: 113,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-23',
      },
      {
        content: ' ',
        offset: 114,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-24',
      },
      {
        content: 'ConcivConfig',
        offset: 115,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-25',
      },
      {
        content: ' ',
        offset: 127,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-26',
      },
      {
        content: '=',
        offset: 128,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-27',
      },
      {content: ' ', offset: 129, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-28'},
      {
        content: '{',
        offset: 130,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-29',
      },
      {content: '\n', offset: 131, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-30'},
      {content: '  ', offset: 132, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-31'},
      {
        content: 'h',
        offset: 134,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-32',
      },
      {content: '\n', offset: 135, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-33'},
      {
        content: '}',
        offset: 136,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-34',
      },
      {content: '\n', offset: 137, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-35'},
      {content: '\n', offset: 138, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-36'},
      {
        content: 'export',
        offset: 139,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-37',
      },
      {
        content: ' ',
        offset: 145,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-38',
      },
      {
        content: 'default',
        offset: 146,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-39',
      },
      {
        content: ' ',
        offset: 153,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-40',
      },
      {
        content: 'defineConfig',
        offset: 154,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-41',
      },
      {
        content: '({',
        offset: 166,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-42',
      },
      {content: '\n', offset: 168, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-43'},
      {content: '  ', offset: 169, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-44'},
      {
        content: 'plugins: [',
        offset: 171,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-45',
      },
      {
        content: 'conciv',
        offset: 181,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-46',
      },
      {
        content: '(options)],',
        offset: 187,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-47',
      },
      {content: '\n', offset: 198, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-48'},
      {
        content: '})',
        offset: 199,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-49',
      },
      {content: '\n', offset: 201, key: '1phCVA4g4AzmR3mXdz4DBU_VbMtQVddaNcd9ZPZvbHQ-50'},
    ],
    lineNumbers: false,
    bg: '#fff;--shiki-dark-bg:#24292e',
    fg: '#24292e;--shiki-dark:#e1e4e8',
    themeName: 'shiki-themes github-light github-dark',
    lang: 'ts',
  },
  {
    code: "import type {NextConfig} from 'next'\nimport {withConciv} from '@conciv/it/plugin/nextjs'\n\nconst nextConfig: NextConfig = {}\n\nexport default withConciv(nextConfig)",
    hash: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk',
    tokens: [
      {
        content: 'import',
        offset: 0,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-0',
      },
      {
        content: ' ',
        offset: 6,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-1',
      },
      {
        content: 'type',
        offset: 7,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-2',
      },
      {content: ' ', offset: 11, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-3'},
      {
        content: '{NextConfig}',
        offset: 12,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-4',
      },
      {content: ' ', offset: 24, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-5'},
      {
        content: 'from',
        offset: 25,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-6',
      },
      {
        content: ' ',
        offset: 29,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-7',
      },
      {
        content: "'next'",
        offset: 30,
        htmlStyle: {color: '#032F62', '--shiki-dark': '#9ECBFF'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-8',
      },
      {content: '\n', offset: 36, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-9'},
      {
        content: 'import',
        offset: 37,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-10',
      },
      {content: ' ', offset: 43, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-11'},
      {
        content: '{withConciv}',
        offset: 44,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-12',
      },
      {content: ' ', offset: 56, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-13'},
      {
        content: 'from',
        offset: 57,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-14',
      },
      {
        content: ' ',
        offset: 61,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-15',
      },
      {
        content: "'@conciv/it/plugin/nextjs'",
        offset: 62,
        htmlStyle: {color: '#032F62', '--shiki-dark': '#9ECBFF'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-16',
      },
      {content: '\n', offset: 88, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-17'},
      {content: '\n', offset: 89, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-18'},
      {
        content: 'const',
        offset: 90,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-19',
      },
      {
        content: ' ',
        offset: 95,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-20',
      },
      {
        content: 'nextConfig',
        offset: 96,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-21',
      },
      {
        content: ':',
        offset: 106,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-22',
      },
      {
        content: ' ',
        offset: 107,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-23',
      },
      {
        content: 'NextConfig',
        offset: 108,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-24',
      },
      {
        content: ' ',
        offset: 118,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-25',
      },
      {
        content: '=',
        offset: 119,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-26',
      },
      {content: ' ', offset: 120, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-27'},
      {
        content: '{}',
        offset: 121,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-28',
      },
      {content: '\n', offset: 123, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-29'},
      {content: '\n', offset: 124, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-30'},
      {
        content: 'export',
        offset: 125,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-31',
      },
      {
        content: ' ',
        offset: 131,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-32',
      },
      {
        content: 'default',
        offset: 132,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-33',
      },
      {
        content: ' ',
        offset: 139,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-34',
      },
      {
        content: 'withConciv',
        offset: 140,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-35',
      },
      {
        content: '(nextConfig)',
        offset: 150,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-36',
      },
      {content: '\n', offset: 162, key: '3y-PnY6aG_VSqpOD86f3hd4XcCKWhc-8vQEVXdOu0zk-37'},
    ],
    lineNumbers: false,
    bg: '#fff;--shiki-dark-bg:#24292e',
    fg: '#24292e;--shiki-dark:#e1e4e8',
    themeName: 'shiki-themes github-light github-dark',
    lang: 'ts',
  },
  {
    code: "const conciv = require('@conciv/it/plugin/webpack')\n\nmodule.exports = {\n  plugins: [conciv.default()],\n}",
    hash: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs',
    tokens: [
      {
        content: 'const',
        offset: 0,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-0',
      },
      {
        content: ' ',
        offset: 5,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-1',
      },
      {
        content: 'conciv',
        offset: 6,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-2',
      },
      {
        content: ' ',
        offset: 12,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-3',
      },
      {
        content: '=',
        offset: 13,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-4',
      },
      {
        content: ' ',
        offset: 14,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-5',
      },
      {
        content: 'require',
        offset: 15,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-6',
      },
      {
        content: '(',
        offset: 22,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-7',
      },
      {
        content: "'@conciv/it/plugin/webpack'",
        offset: 23,
        htmlStyle: {color: '#032F62', '--shiki-dark': '#9ECBFF'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-8',
      },
      {
        content: ')',
        offset: 50,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-9',
      },
      {content: '\n', offset: 51, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-10'},
      {content: '\n', offset: 52, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-11'},
      {
        content: 'module',
        offset: 53,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-12',
      },
      {
        content: '.',
        offset: 59,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-13',
      },
      {
        content: 'exports',
        offset: 60,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-14',
      },
      {
        content: ' ',
        offset: 67,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-15',
      },
      {
        content: '=',
        offset: 68,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-16',
      },
      {content: ' ', offset: 69, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-17'},
      {
        content: '{',
        offset: 70,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-18',
      },
      {content: '\n', offset: 71, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-19'},
      {content: '  ', offset: 72, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-20'},
      {
        content: 'plugins: [conciv.',
        offset: 74,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-21',
      },
      {
        content: 'default',
        offset: 91,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-22',
      },
      {
        content: '()],',
        offset: 98,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-23',
      },
      {content: '\n', offset: 102, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-24'},
      {
        content: '}',
        offset: 103,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-25',
      },
      {content: '\n', offset: 104, key: 'WbxYhMPkuwaGiEVpPvZte3tecB1IYcccZ3Jdh2t6OJs-26'},
    ],
    lineNumbers: false,
    bg: '#fff;--shiki-dark-bg:#24292e',
    fg: '#24292e;--shiki-dark:#e1e4e8',
    themeName: 'shiki-themes github-light github-dark',
    lang: 'js',
  },
  {
    code: "const conciv = require('@conciv/it/plugin/rspack')\n\nmodule.exports = {\n  plugins: [conciv.default()],\n}",
    hash: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw',
    tokens: [
      {
        content: 'const',
        offset: 0,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-0',
      },
      {
        content: ' ',
        offset: 5,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-1',
      },
      {
        content: 'conciv',
        offset: 6,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-2',
      },
      {
        content: ' ',
        offset: 12,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-3',
      },
      {
        content: '=',
        offset: 13,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-4',
      },
      {
        content: ' ',
        offset: 14,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-5',
      },
      {
        content: 'require',
        offset: 15,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-6',
      },
      {
        content: '(',
        offset: 22,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-7',
      },
      {
        content: "'@conciv/it/plugin/rspack'",
        offset: 23,
        htmlStyle: {color: '#032F62', '--shiki-dark': '#9ECBFF'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-8',
      },
      {
        content: ')',
        offset: 49,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-9',
      },
      {content: '\n', offset: 50, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-10'},
      {content: '\n', offset: 51, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-11'},
      {
        content: 'module',
        offset: 52,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-12',
      },
      {
        content: '.',
        offset: 58,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-13',
      },
      {
        content: 'exports',
        offset: 59,
        htmlStyle: {color: '#005CC5', '--shiki-dark': '#79B8FF'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-14',
      },
      {
        content: ' ',
        offset: 66,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-15',
      },
      {
        content: '=',
        offset: 67,
        htmlStyle: {color: '#D73A49', '--shiki-dark': '#F97583'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-16',
      },
      {content: ' ', offset: 68, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-17'},
      {
        content: '{',
        offset: 69,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-18',
      },
      {content: '\n', offset: 70, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-19'},
      {content: '  ', offset: 71, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-20'},
      {
        content: 'plugins: [conciv.',
        offset: 73,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-21',
      },
      {
        content: 'default',
        offset: 90,
        htmlStyle: {color: '#6F42C1', '--shiki-dark': '#B392F0'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-22',
      },
      {
        content: '()],',
        offset: 97,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-23',
      },
      {content: '\n', offset: 101, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-24'},
      {
        content: '}',
        offset: 102,
        htmlStyle: {color: '#24292E', '--shiki-dark': '#E1E4E8'},
        key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-25',
      },
      {content: '\n', offset: 103, key: 'OaSnrm0gOCHg4SXjiEunS_CDqOVh_mhZKuUzccRjPsw-26'},
    ],
    lineNumbers: false,
    bg: '#fff;--shiki-dark-bg:#24292e',
    fg: '#24292e;--shiki-dark:#e1e4e8',
    themeName: 'shiki-themes github-light github-dark',
    lang: 'js',
  },
]

export const SNIPPET_TWOSLASH: SnippetTwoslash[] = [
  {
    id: 'vite',
    hovers: [
      {
        target: 'defineConfig',
        occurrence: 0,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(alias) </span><span style="color:#D73A49;--shiki-dark:#F97583">function</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> defineConfig</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#E36209;--shiki-dark:#FFAB70">config</span><span style="color:#D73A49;--shiki-dark:#F97583">:</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> UserConfig</span><span style="color:#24292E;--shiki-dark:#E1E4E8">)</span><span style="color:#D73A49;--shiki-dark:#F97583">:</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> UserConfig</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> (+</span><span style="color:#005CC5;--shiki-dark:#79B8FF">5</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> overloads</span><span style="color:#24292E;--shiki-dark:#E1E4E8">)</span></span>\n<span class="line"><span style="color:#D73A49;--shiki-dark:#F97583">import</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> defineConfig</span></span>',
        docs: 'Type helper to make it easier to use vite.config.ts\naccepts a direct \n{@link \nUserConfig\n}\n object, or a function that returns it.\nThe function receives a \n{@link \nConfigEnv\n}\n object.',
      },
      {
        target: 'conciv',
        occurrence: 0,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(alias) </span><span style="color:#D73A49;--shiki-dark:#F97583">const</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> conciv</span><span style="color:#D73A49;--shiki-dark:#F97583">:</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> (</span><span style="color:#E36209;--shiki-dark:#FFAB70">options</span><span style="color:#D73A49;--shiki-dark:#F97583">?:</span><span style="color:#D73A49;--shiki-dark:#F97583"> import</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#032F62;--shiki-dark:#9ECBFF">"@conciv/protocol/config-types"</span><span style="color:#24292E;--shiki-dark:#E1E4E8">).</span><span style="color:#6F42C1;--shiki-dark:#B392F0">ConcivConfig</span><span style="color:#D73A49;--shiki-dark:#F97583"> |</span><span style="color:#005CC5;--shiki-dark:#79B8FF"> undefined</span><span style="color:#24292E;--shiki-dark:#E1E4E8">) </span><span style="color:#D73A49;--shiki-dark:#F97583">=></span><span style="color:#D73A49;--shiki-dark:#F97583"> import</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#032F62;--shiki-dark:#9ECBFF">"vite"</span><span style="color:#24292E;--shiki-dark:#E1E4E8">).</span><span style="color:#6F42C1;--shiki-dark:#B392F0">Plugin</span><span style="color:#24292E;--shiki-dark:#E1E4E8">&#x3C;</span><span style="color:#005CC5;--shiki-dark:#79B8FF">any</span><span style="color:#24292E;--shiki-dark:#E1E4E8">> </span><span style="color:#D73A49;--shiki-dark:#F97583">|</span><span style="color:#D73A49;--shiki-dark:#F97583"> import</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#032F62;--shiki-dark:#9ECBFF">"vite"</span><span style="color:#24292E;--shiki-dark:#E1E4E8">).</span><span style="color:#6F42C1;--shiki-dark:#B392F0">Plugin</span><span style="color:#24292E;--shiki-dark:#E1E4E8">&#x3C;</span><span style="color:#005CC5;--shiki-dark:#79B8FF">any</span><span style="color:#24292E;--shiki-dark:#E1E4E8">>[]</span></span>\n<span class="line"><span style="color:#D73A49;--shiki-dark:#F97583">import</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> conciv</span></span>',
        docs: null,
      },
      {
        target: 'ConcivConfig',
        occurrence: 0,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(alias) </span><span style="color:#D73A49;--shiki-dark:#F97583">interface</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> ConcivConfig</span></span>\n<span class="line"><span style="color:#6F42C1;--shiki-dark:#B392F0">import</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> ConcivConfig</span></span>',
        docs: null,
      },
      {
        target: 'options',
        occurrence: 0,
        html: '<span class="line"><span style="color:#D73A49;--shiki-dark:#F97583">const</span><span style="color:#005CC5;--shiki-dark:#79B8FF"> options</span><span style="color:#D73A49;--shiki-dark:#F97583">:</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> ConcivConfig</span></span>',
        docs: null,
      },
      {
        target: 'ConcivConfig',
        occurrence: 1,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(alias) </span><span style="color:#D73A49;--shiki-dark:#F97583">interface</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> ConcivConfig</span></span>\n<span class="line"><span style="color:#6F42C1;--shiki-dark:#B392F0">import</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> ConcivConfig</span></span>',
        docs: null,
      },
      {
        target: 'h',
        occurrence: 0,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(property) </span><span style="color:#6F42C1;--shiki-dark:#B392F0">h</span><span style="color:#24292E;--shiki-dark:#E1E4E8">: any</span></span>',
        docs: null,
      },
      {
        target: 'defineConfig',
        occurrence: 1,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(alias) </span><span style="color:#6F42C1;--shiki-dark:#B392F0">defineConfig</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(config: UserConfig): </span><span style="color:#6F42C1;--shiki-dark:#B392F0">UserConfig</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> (</span><span style="color:#D73A49;--shiki-dark:#F97583">+</span><span style="color:#005CC5;--shiki-dark:#79B8FF">5</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> overloads)</span></span>\n<span class="line"><span style="color:#D73A49;--shiki-dark:#F97583">import</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> defineConfig</span></span>',
        docs: 'Type helper to make it easier to use vite.config.ts\naccepts a direct \n{@link \nUserConfig\n}\n object, or a function that returns it.\nThe function receives a \n{@link \nConfigEnv\n}\n object.',
      },
      {
        target: 'plugins',
        occurrence: 0,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(property) UserConfig.plugins</span><span style="color:#D73A49;--shiki-dark:#F97583">?:</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> PluginOption[] </span><span style="color:#D73A49;--shiki-dark:#F97583">|</span><span style="color:#005CC5;--shiki-dark:#79B8FF"> undefined</span></span>',
        docs: 'Array of vite plugins to use.',
      },
      {
        target: 'conciv',
        occurrence: 1,
        html: '<span class="line"><span style="color:#24292E;--shiki-dark:#E1E4E8">(alias) </span><span style="color:#6F42C1;--shiki-dark:#B392F0">conciv</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(options</span><span style="color:#D73A49;--shiki-dark:#F97583">?:</span><span style="color:#D73A49;--shiki-dark:#F97583"> import</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#032F62;--shiki-dark:#9ECBFF">"@conciv/protocol/config-types"</span><span style="color:#24292E;--shiki-dark:#E1E4E8">).ConcivConfig </span><span style="color:#D73A49;--shiki-dark:#F97583">|</span><span style="color:#005CC5;--shiki-dark:#79B8FF"> undefined</span><span style="color:#24292E;--shiki-dark:#E1E4E8">): </span><span style="color:#D73A49;--shiki-dark:#F97583">import</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#032F62;--shiki-dark:#9ECBFF">"vite"</span><span style="color:#24292E;--shiki-dark:#E1E4E8">).Plugin</span><span style="color:#D73A49;--shiki-dark:#F97583">&#x3C;</span><span style="color:#24292E;--shiki-dark:#E1E4E8">any</span><span style="color:#D73A49;--shiki-dark:#F97583">></span><span style="color:#D73A49;--shiki-dark:#F97583"> |</span><span style="color:#D73A49;--shiki-dark:#F97583"> import</span><span style="color:#24292E;--shiki-dark:#E1E4E8">(</span><span style="color:#032F62;--shiki-dark:#9ECBFF">"vite"</span><span style="color:#24292E;--shiki-dark:#E1E4E8">).Plugin</span><span style="color:#D73A49;--shiki-dark:#F97583">&#x3C;</span><span style="color:#24292E;--shiki-dark:#E1E4E8">any</span><span style="color:#D73A49;--shiki-dark:#F97583">></span><span style="color:#24292E;--shiki-dark:#E1E4E8">[]</span></span>\n<span class="line"><span style="color:#D73A49;--shiki-dark:#F97583">import</span><span style="color:#24292E;--shiki-dark:#E1E4E8"> conciv</span></span>',
        docs: null,
      },
      {
        target: 'options',
        occurrence: 1,
        html: '<span class="line"><span style="color:#D73A49;--shiki-dark:#F97583">const</span><span style="color:#005CC5;--shiki-dark:#79B8FF"> options</span><span style="color:#D73A49;--shiki-dark:#F97583">:</span><span style="color:#6F42C1;--shiki-dark:#B392F0"> ConcivConfig</span></span>',
        docs: null,
      },
    ],
    completion: {target: 'h', items: ['harness', 'harnessBin']},
  },
]
