import {describe, it, expect} from 'vitest'
import {mkdtempSync, mkdirSync, writeFileSync, rmSync, utimesSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {
  parseHistory,
  parseSessionMeta,
  claudeHistory,
  contextTokensFromTranscript,
  encodeProjectDir,
  listSessions,
  withinProject,
} from '../src/claude/history.js'

function seed(home: string, cwd: string, id: string, body: string, mtimeSec: number) {
  const dir = join(home, '.claude', 'projects', encodeProjectDir(cwd))
  mkdirSync(dir, {recursive: true})
  const p = join(dir, `${id}.jsonl`)
  writeFileSync(p, body)
  utimesSync(p, mtimeSec, mtimeSec)
}

describe('parseHistory', () => {
  it('keeps user messages whose content is a plain string', () => {
    const jsonl = [
      JSON.stringify({type: 'user', message: {role: 'user', content: 'what else can you do?'}}),
      JSON.stringify({
        type: 'assistant',
        message: {role: 'assistant', content: [{type: 'text', text: 'Lots of things.'}]},
      }),
    ].join('\n')

    const msgs = parseHistory(jsonl)
    const roles = msgs.map((m) => m.role)
    expect(roles).toContain('user')
    expect(roles).toContain('assistant')

    const user = msgs.find((m) => m.role === 'user')
    expect(user?.parts).toContainEqual({type: 'text', content: 'what else can you do?'})
  })

  it('merges consecutive assistant records that share a message.id', () => {
    const jsonl = [
      JSON.stringify({type: 'user', message: {role: 'user', content: "what's on the page now?"}}),
      JSON.stringify({
        type: 'assistant',
        message: {id: 'msg_A', role: 'assistant', content: [{type: 'thinking', thinking: 'Let me take a snapshot.'}]},
      }),
      JSON.stringify({
        type: 'assistant',
        message: {
          id: 'msg_A',
          role: 'assistant',
          content: [{type: 'tool_use', id: 'toolu_1', name: 'mcp__conciv__page_snapshot', input: {verb: 'snapshot'}}],
        },
      }),
      JSON.stringify({
        type: 'user',
        message: {role: 'user', content: [{type: 'tool_result', tool_use_id: 'toolu_1', content: 'ok'}]},
      }),
      JSON.stringify({
        type: 'assistant',
        message: {id: 'msg_B', role: 'assistant', content: [{type: 'text', text: 'Same as before.'}]},
      }),
    ].join('\n')

    const msgs = parseHistory(jsonl)
    const assistants = msgs.filter((m) => m.role === 'assistant')
    expect(assistants).toHaveLength(2)
    expect(assistants[0]?.parts.map((p) => p.type)).toEqual(['thinking', 'tool-call', 'tool-result'])
    expect(assistants[1]?.parts.map((p) => p.type)).toEqual(['text'])
  })

  it('strips the plugin-scoped conciv namespace adopted sessions use', () => {
    const jsonl = JSON.stringify({
      type: 'assistant',
      message: {
        id: 'msg_C',
        role: 'assistant',
        content: [
          {
            type: 'tool_use',
            id: 'toolu_2',
            name: 'mcp__plugin_conciv-connect_conciv__page_snapshot',
            input: {verb: 'snapshot'},
          },
        ],
      },
    })

    const call = parseHistory(jsonl)[0]?.parts[0]
    expect(call).toMatchObject({type: 'tool-call', name: 'page_snapshot'})
  })

  it('leaves other plugin servers fully qualified', () => {
    const jsonl = JSON.stringify({
      type: 'assistant',
      message: {
        id: 'msg_D',
        role: 'assistant',
        content: [{type: 'tool_use', id: 'toolu_3', name: 'mcp__plugin_context7_context7__query-docs', input: {}}],
      },
    })

    const call = parseHistory(jsonl)[0]?.parts[0]
    expect(call).toMatchObject({type: 'tool-call', name: 'mcp__plugin_context7_context7__query-docs'})
  })
})

const taskNotification = JSON.stringify({
  type: 'user',
  origin: {kind: 'task-notification'},
  message: {role: 'user', content: 'Background task 3fa1 completed'},
})
const interrupted = JSON.stringify({
  type: 'user',
  message: {role: 'user', content: '[Request interrupted by user]'},
})
const interruptedForToolUse = JSON.stringify({
  type: 'user',
  interruptedMessageId: 'msg_interrupted',
  message: {role: 'user', content: '[Request interrupted by user for tool use]'},
})
const noResponseRequested = JSON.stringify({
  type: 'user',
  message: {role: 'user', content: 'No response requested.'},
})
const metaSkillBody = JSON.stringify({
  type: 'user',
  isMeta: true,
  message: {role: 'user', content: 'You are running the octocat skill. Follow SKILL.md exactly.'},
})
const metaImageRef = JSON.stringify({
  type: 'user',
  isMeta: true,
  message: {role: 'user', content: [{type: 'text', text: '[Image #1]'}]},
})
const metaLocalCommandCaveat = JSON.stringify({
  type: 'user',
  isMeta: true,
  message: {
    role: 'user',
    content: 'Caveat: The messages below were generated by the user while running local commands.',
  },
})
const compactSummary = JSON.stringify({
  type: 'user',
  isCompactSummary: true,
  message: {role: 'user', content: 'This session is being continued from a previous conversation.'},
})
const slashCommandMarker = JSON.stringify({
  type: 'user',
  message: {
    role: 'user',
    content:
      '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
  },
})
const machineryLines = [
  taskNotification,
  interrupted,
  interruptedForToolUse,
  noResponseRequested,
  metaSkillBody,
  metaImageRef,
  metaLocalCommandCaveat,
  compactSummary,
  slashCommandMarker,
]

describe('parseHistory machinery filtering', () => {
  it('drops every claude machinery record instead of rendering it as a user turn', () => {
    expect(parseHistory(machineryLines.join('\n'))).toEqual([])
  })

  it('keeps genuine typed, queued-with-image, and SDK-style (no origin) user messages', () => {
    const jsonl = [
      JSON.stringify({type: 'user', origin: {kind: 'human'}, message: {role: 'user', content: 'fix the header'}}),
      JSON.stringify({
        type: 'user',
        origin: {kind: 'human'},
        message: {
          role: 'user',
          content: [
            {type: 'image', source: {type: 'base64', media_type: 'image/png', data: 'iVBOR'}},
            {type: 'text', text: 'match this mock'},
          ],
        },
      }),
      JSON.stringify({type: 'user', message: {role: 'user', content: 'and ship it'}}),
    ].join('\n')

    const msgs = parseHistory(jsonl)
    expect(msgs.map((m) => m.role)).toEqual(['user', 'user', 'user'])
    expect(msgs.flatMap((m) => m.parts)).toEqual([
      {type: 'text', content: 'fix the header'},
      {type: 'text', content: 'match this mock'},
      {type: 'text', content: 'and ship it'},
    ])
  })

  it('keeps prose that mentions capitalised markup', () => {
    const jsonl = JSON.stringify({type: 'user', message: {role: 'user', content: '<Button>Save</Button>'}})
    expect(parseHistory(jsonl)[0]?.parts).toEqual([{type: 'text', content: '<Button>Save</Button>'}])
  })

  it('still attaches tool results carried by machinery-adjacent user records', () => {
    const jsonl = [
      JSON.stringify({
        type: 'assistant',
        message: {
          id: 'msg_T',
          role: 'assistant',
          content: [{type: 'tool_use', id: 'toolu_9', name: 'Read', input: {}}],
        },
      }),
      JSON.stringify({
        type: 'user',
        message: {role: 'user', content: [{type: 'tool_result', tool_use_id: 'toolu_9', content: 'file body'}]},
      }),
      interrupted,
    ].join('\n')

    const msgs = parseHistory(jsonl)
    expect(msgs).toHaveLength(1)
    expect(msgs[0]?.parts.map((p) => p.type)).toEqual(['tool-call', 'tool-result'])
  })
})

describe('parseSessionMeta machinery filtering', () => {
  it('derives the title from the first genuine user message', () => {
    const jsonl = [
      ...machineryLines,
      JSON.stringify({type: 'user', message: {role: 'user', content: 'rename the settings panel'}}),
      JSON.stringify({type: 'assistant', message: {role: 'assistant', content: [{type: 'text', text: 'done'}]}}),
    ].join('\n')
    expect(parseSessionMeta('s', jsonl, 1).derivedTitle).toBe('rename the settings panel')
  })

  it('counts only genuine turns and never previews machinery', () => {
    const jsonl = [
      JSON.stringify({type: 'user', message: {role: 'user', content: 'rename the settings panel'}}),
      JSON.stringify({type: 'assistant', message: {role: 'assistant', content: [{type: 'text', text: 'done'}]}}),
      ...machineryLines,
    ].join('\n')
    const meta = parseSessionMeta('s', jsonl, 1)
    expect(meta.messageCount).toBe(2)
    expect(meta.lastMessage).toBe('done')
  })
})

describe('contextTokensFromTranscript', () => {
  const assistant = (usage: Record<string, number>, extra: Record<string, unknown> = {}) =>
    JSON.stringify({
      type: 'assistant',
      message: {role: 'assistant', content: [{type: 'text', text: 'ok'}], usage},
      ...extra,
    })

  it('reports the LAST request occupancy, never the cumulative turn sum', () => {
    const jsonl = [
      assistant({input_tokens: 4, cache_creation_input_tokens: 900, cache_read_input_tokens: 89000}),
      JSON.stringify({type: 'user', message: {role: 'user', content: [{type: 'tool_result', tool_use_id: 't1'}]}}),
      assistant({input_tokens: 2, cache_creation_input_tokens: 750, cache_read_input_tokens: 92000}),
    ].join('\n')
    expect(contextTokensFromTranscript(jsonl)).toBe(2 + 750 + 92000)
  })

  it('ignores sub-agent (sidechain) records', () => {
    const jsonl = [
      assistant({input_tokens: 2, cache_creation_input_tokens: 750, cache_read_input_tokens: 92000}),
      assistant({input_tokens: 5, cache_read_input_tokens: 500000}, {isSidechain: true}),
    ].join('\n')
    expect(contextTokensFromTranscript(jsonl)).toBe(2 + 750 + 92000)
  })

  it('returns undefined when no assistant usage is present', () => {
    const jsonl = JSON.stringify({type: 'user', message: {role: 'user', content: 'hi'}})
    expect(contextTokensFromTranscript(jsonl)).toBeUndefined()
  })

  it('is wired onto claudeHistory', () => {
    expect(claudeHistory.contextTokens).toBe(contextTokensFromTranscript)
  })
})

describe('claudeHistory.nameFromTranscript', () => {
  it('returns the last summary record', () => {
    const jsonl = [
      JSON.stringify({type: 'summary', summary: 'First guess'}),
      JSON.stringify({type: 'user', message: {content: 'hi'}}),
      JSON.stringify({type: 'summary', summary: 'Fix the checkout layout bug'}),
    ].join('\n')
    expect(claudeHistory.nameFromTranscript?.(jsonl)).toBe('Fix the checkout layout bug')
  })

  it('returns null when there is no summary', () => {
    const jsonl = JSON.stringify({type: 'user', message: {content: 'hi'}})
    expect(claudeHistory.nameFromTranscript?.(jsonl)).toBeNull()
  })
})

describe('listSessions', () => {
  it('lists newest-first with title + count', async () => {
    const home = mkdtempSync(join(tmpdir(), 'conciv-home-'))
    const cwd = '/proj/x'
    seed(home, cwd, 'old', JSON.stringify({type: 'user', message: {content: 'first task'}}) + '\n', 1000)
    seed(
      home,
      cwd,
      'new',
      [
        JSON.stringify({type: 'user', message: {content: 'newer task'}}),
        JSON.stringify({type: 'assistant', message: {content: [{type: 'text', text: 'ok'}]}}),
      ].join('\n') + '\n',
      2000,
    )
    const out = await listSessions(cwd, home)
    expect(out.map((s) => s.id)).toEqual(['new', 'old'])
    expect(out[0]).toMatchObject({derivedTitle: 'newer task', messageCount: 2})
    rmSync(home, {recursive: true, force: true})
  })

  it('caps at 50 and does not read the 51st', async () => {
    const home = mkdtempSync(join(tmpdir(), 'conciv-home-'))
    const cwd = '/proj/y'
    for (let i = 0; i < 51; i++)
      seed(
        home,
        cwd,
        `s${String(i).padStart(2, '0')}`,
        JSON.stringify({type: 'user', message: {content: `t${i}`}}) + '\n',
        1000 + i,
      )
    const out = await listSessions(cwd, home)
    expect(out.length).toBe(50)
    expect(out.some((s) => s.id === 's00')).toBe(false)
    rmSync(home, {recursive: true, force: true})
  })

  it('returns [] for a missing dir', async () => {
    expect(await listSessions('/no/such', mkdtempSync(join(tmpdir(), 'conciv-home-')))).toEqual([])
  })
})

describe('withinProject', () => {
  it('rejects traversal and accepts a normal id', () => {
    const home = mkdtempSync(join(tmpdir(), 'conciv-home-'))
    expect(withinProject('/proj', '../../etc/passwd', home)).toBe(false)
    expect(withinProject('/proj', '0c1d2e3f-aaaa-bbbb-cccc-000011112222', home)).toBe(true)
    rmSync(home, {recursive: true, force: true})
  })
})

describe('parseSessionMeta', () => {
  it('extracts model + token totals + last message from a transcript', () => {
    const jsonl = [
      JSON.stringify({type: 'system', session_id: 'tok', model: 'claude-opus-4-8'}),
      JSON.stringify({type: 'user', message: {content: 'hi there'}}),
      JSON.stringify({type: 'assistant', message: {content: [{type: 'text', text: 'the reply'}]}}),
      JSON.stringify({type: 'result', usage: {input_tokens: 10, output_tokens: 5}}),
    ].join('\n')
    const meta = parseSessionMeta('tok', jsonl, 123)
    expect(meta.model).toBe('claude-opus-4-8')
    expect(meta.updatedAt).toBe(123)
    expect(meta.totalTokens).toBe(15)
    expect(meta.lastMessage).toBe('the reply')
  })
})
